
server:
  port: 8080

spring:
  application:
    name: back-end

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    name: backend-process
    url: jdbc:h2:mem:test # In-Memory mode 
    jdbc-url: jdbc:h2:mem:test
    username: sa
    password: 
  sql:
    init:
      mode: always
