DROP TABLE IF EXISTS USER_MST;
CREATE TABLE USER_MST
(
    username   VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255),
    PRIMARY KEY (username)
);

DROP TABLE IF EXISTS CMN_CODE;
CREATE TABLE CMN_CODE
(
    CODE_CD VARCHAR(255) NOT NULL COMMENT '코드아이디',
    CODE_NM VARCHAR(255) NOT NULL COMMENT '코드명칭',
    CODE_LVL SMALLINT NOT NULL COMMENT '코드레벨',
    P_CODE_CD VARCHAR(255) COMMENT '상위코드아이디',
    DSP_ORDER SMALLINT DEFAULT 1 COMMENT '출력순서',
    USE_YN CHAR(1) DEFAULT 'Y' COMMENT '사용여부',
    EXP_FR_DT DATE COMMENT '유효기간 시작일자',
    EXP_TO_DT DATE COMMENT '유효기간 종료일자',
    ATTR1_JSON VARCHAR(1000) COMMENT '속성1JSON',
    ATTR1_VAL VARCHAR(255) COMMENT '속성1값',
    ATTR2_JSON VARCHAR(1000) COMMENT '속성2JSON',
    ATTR2_VAL VARCHAR(255) COMMENT '속성2값',
    ATTR3_JSON VARCHAR(1000) COMMENT '속성3JSON',
    ATTR3_VAL VARCHAR(255) COMMENT '속성3값',
    ATTR4_JSON VARCHAR(1000) COMMENT '속성4JSON',
    ATTR4_VAL VARCHAR(255) COMMENT '속성4값',
    ATTR5_JSON VARCHAR(1000) COMMENT '속성5JSON',
    ATTR5_VAL VARCHAR(255) COMMENT '속성5값',
    ATTR6_JSON VARCHAR(1000) COMMENT '속성6JSON',
    ATTR6_VAL VARCHAR(255) COMMENT '속성6값',
    ATTR7_JSON VARCHAR(1000) COMMENT '속성71JSON',
    ATTR7_VAL VARCHAR(255) COMMENT '속성7값',
    ATTR8_JSON VARCHAR(1000) COMMENT '속성8JSON',
    ATTR8_VAL VARCHAR(255) COMMENT '속성8값',
    ATTR9_JSON VARCHAR(1000) COMMENT '속성9JSON',
    ATTR9_VAL VARCHAR(255) COMMENT '속성9값',
    ATTR10_JSON VARCHAR(1000) COMMENT '속성10JSON',
    ATTR10_VAL VARCHAR(255) COMMENT '속성10값',
    CRT_TM DATETIME DEFAULT CURRENT_TIMESTAMP,
    CRT_ID VARCHAR(50),
    UPD_TM DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPD_ID VARCHAR(50),
    PRIMARY KEY (CODE_CD)
)  COMMENT '공통코드';


, A.CODE_CD
, A.CODE_NM
, A.CODE_LVL
, A.P_CODE_CD
, A.DSP_ORDER
, A.USE_YN
, A.EXP_FR_DT
, A.EXP_TO_DT
, A.ATTR1_JSON
, A.ATTR1_VAL
, A.ATTR2_JSON
, A.ATTR2_VAL
, A.ATTR3_JSON
, A.ATTR3_VAL
, A.ATTR4_JSON
, A.ATTR4_VAL
, A.ATTR5_JSON
, A.ATTR5_VAL
, A.ATTR6_JSON
, A.ATTR6_VAL
, A.ATTR7_JSON
, A.ATTR7_VAL
, A.ATTR8_JSON
, A.ATTR8_VAL
, A.ATTR9_JSON
, A.ATTR9_VAL
, A.ATTR10_JSON
, A.ATTR10_VAL


, CODE_CD
, CODE_NM
, CODE_LVL
, P_CODE_CD
, DSP_ORDER
, USE_YN
, EXP_FR_DT
, EXP_TO_DT
, ATTR1_JSON
, ATTR1_VAL
, ATTR2_JSON
, ATTR2_VAL
, ATTR3_JSON
, ATTR3_VAL
, ATTR4_JSON
, ATTR4_VAL
, ATTR5_JSON
, ATTR5_VAL
, ATTR6_JSON
, ATTR6_VAL
, ATTR7_JSON
, ATTR7_VAL
, ATTR8_JSON
, ATTR8_VAL
, ATTR9_JSON
, ATTR9_VAL
, ATTR10_JSON
, ATTR10_VAL